# Generated by Django 3.1 on 2020-08-16 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20200813_1808'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='overview',
            field=models.CharField(default='', max_length=2000),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.CharField(default='', max_length=2000),
        ),
    ]
