# Generated by Django 3.1 on 2020-08-19 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_auto_20200819_1425'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='items_json',
        ),
        migrations.AddField(
            model_name='order',
            name='orderID',
            field=models.CharField(default='', max_length=5000),
        ),
        migrations.AddField(
            model_name='order',
            name='order_products',
            field=models.CharField(default='', max_length=5000),
        ),
    ]
